version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-backend
    ports:
      - "3000:3000"