name: Build and deploy Angular app to Azure Web App

on:
  push:
    branches:
      - test-githug-actions
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build-poker

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: jjlba
          publish-profile: ${{ secrets.JJLBA }}
          package: ./dist/poker-app/browser
